#!/usr/bin/env python

import argparse
from template import *

change_to_source_dir()

parser = argparse.ArgumentParser(prog='generate-test-case', description='Generate a CppUnit test class')
parser.add_argument('name', metavar='test_class_name',
                    help='Name of the new test class without the "Test"-postfix')
parser.add_argument('methods', nargs='*',
                    help='Test methods the test class should have')

args = parser.parse_args()
args.uppercase_name = args.name.upper()

eval_template("scripts/test-case-template/source-file",
              "src/test/" + args.name + "Test.cpp", args)
eval_template("scripts/test-case-template/header-file",
              "src/test/" + args.name + "Test.h", args)

